# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.Repository.LocalPath)'
    MachineNames: '13.90.244.30'
    AdminUserName: 'FLDEV'
    AdminPassword: 'S@dev963258741#'
    TargetPath: 'C:\Users\FLDEV'
  